---
# - name: mount volume
#   become: yes
#   docker_volume:
#     name: env_data

- name: Copy site1.env file to host
  become: yes
  ansible.builtin.copy:
    src: site1.env
    dest: /tmp/.
    mode: "0600"

- name: Copy site2.env file to host
  become: yes
  ansible.builtin.copy:
    src: site2.env
    dest: /tmp/.
    mode: "0600"

- name: Deploy application
  become: yes
  docker_container:
    image: valerionet/hometask:latest
    name: hometask
    restart_policy: always
    state: started
    restart: yes
    recreate: yes
    ports:
      - "8000:8000"
    # volumes:
    #   - env_data:/var/lib/app

- name: Copy .env file to container
  become: yes
  ansible.builtin.shell: docker cp /tmp/site1.env hometask:/usr/src/app/.env

- name: Restart hometask app
  become: yes
  community.docker.docker_container:
    name: hometask
    # image: someuser/appimage
    state: started
    restart: yes
