---
- name: Copy site1.env and site2.env files to host
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /tmp/.
    mode: "0600"
  loop:
    - site1.env
    - site2.env

- name: Deploy application
  become: yes
  docker_container:
    image: valerionet/hometask:latest
    name: "hometask{{ item }}"
    restart_policy: always
    state: started
    restart: yes
    recreate: yes
    ports:
      - "800{{ item }}:8000"
  loop:
    - 1
    - 2
    - 3

- name: Copy .env file to container
  become: yes
  ansible.builtin.shell: "docker cp /tmp/site1.env hometask{{ item }}:/usr/src/app/.env"
  loop:
    - 1
    - 2
    - 3

- name: Restart hometask app
  become: yes
  community.docker.docker_container:
    name: "hometask{{ item }}"
    state: started
    restart: yes
  loop:
    - 1
    - 2
    - 3
