---
- name: Install service packages
  become: yes
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    state: latest
    update_cache: yes
  loop:
    - htop
    - lsof
    - mcedit
    - dstat
    - mtr
    - python3-pip
  tags:
    - dependencies

- include_tasks: app.yml
