---
- name: Install dependency packages
  become: yes
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    state: latest
    update_cache: yes
  loop:
    - htop
    - lsof
    - gnupg2
    - mcedit
    - dstat
    - mtr
    - python3-pip
    - git
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - curl
  tags:
    - dependencies

- include_tasks: docker.yml

- include_tasks: app.yml
