---
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution | lower  }}.yml"

- name: Download Zabbix repo package
  get_url:
    url: "{{ zabbix_repo_url }}"
    dest: /tmp/zabbix_srv.deb

- name: Install Zabbix repo
  become: yes
  apt:
    deb: /tmp/zabbix_srv.deb
    state: present

- name: Install Zabbix server, frontend, and agent
  become: yes
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    state: present
    update_cache: yes
  loop:
    - apache2
    - apache2-utils
    - zabbix-server-pgsql
    - zabbix-frontend-php
    - certbot
    - python3-certbot-nginx
    - python3-certbot-apache
