- name: Install PostgreSQL
  apt: pkg={{ item }} update_cache=yes state=present
  become: yes
  tags: postgres
  with_items:
    - postgresql
    - postgresql-client
    - postgresql-contrib
    - libpq-dev

- name: Configure PostgreSQL. Set listen_addresses.
  lineinfile: dest=/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    regexp="listen_addresses =" line="listen_addresses = '*'" state=present
  notify: restart postgresql
  become: yes
  tags: postgres

- name: Create PostgreSQL DB
  postgresql_db: name={{ postgresql_db_name }}
  become: yes
  become_user: postgres
  tags: postgres

- name: Create PostgreSQL user and grant access
  postgresql_user: db={{ postgresql_db_name }} user={{ postgresql_db_user }} password={{ postgresql_db_user_password }}
  become: yes
  become_user: postgres
  tags: postgres

- name: Create schema "base"
  postgresql_schema: db={{ postgresql_db_name }} name=base
  become: yes
  become_user: postgres
  tags: postgres

- name: Create table
  postgresql_table:
    db: "{{ postgresql_db_name }}"
    name: base.users
    columns:
      - username    varchar(20) not null primary key
      - birthday    date        not null
  become: yes
  become_user: postgres
  tags: postgres

- name: Create user having only necessary access privileges
  postgresql_user:
    db: "{{ postgresql_db_name }}"
    name: "{{ postgresql_db_user }}"
    password: "{{ postgresql_db_user_password }}"
    priv: "CONNECT/base:USAGE/base.users:SELECT,INSERT,UPDATE"
  become: yes
  become_user: postgres
  tags: postgres
