- block:
    - name: Update the apt package index
      become: yes
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes
    - name: Install packages for apt add repository over HTTPS
      become: yes
      apt:
        name: "{{ packagesdep }}"
        force_apt_get: yes
        state: latest
        update_cache: yes
      vars:
        packagesdep:
          - git
          - apt-transport-https
          - ca-certificates
          - wget
          - software-properties-common
          - gnupg2
          - curl
          - python3
          - python3-pip
    # - name: Add Apt signing key from official docker repo
    #   apt_key:
    #     url: https://download.docker.com/linux/debian/gpg
    #     state: present
    # - name: add docker official repository for Debian Stretch
    #   apt_repository:
    #     repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    #     state: present
    # - name: Index new repo into the cache
    #   become: yes
    #   apt:
    #     name: "*"
    #     state: latest
    #     update_cache: yes
    #     force_apt_get: yes
    # - name: Install docker
    #   apt:
    #     name: "docker-ce"
    #     state: latest

    - name: Install Docker SDK for Python
      pip:
        name: "docker<5"
        executable: pip3

    - name: Setup more docker dependencies
      pip:
        name: "websocket-client<1"
        executable: pip3

    - name: Restart Docker service
      service:
        name: docker
        enabled: yes
        state: restarted
        daemon_reload: yes

    - name: Deploy application
      docker_container:
        image: valerionet/hometask:0.2
        name: hometask
        restart_policy: always
        state: started
        restart: yes
        recreate: yes
        ports:
          - "8000:8000"
        # volumes:
