- block:
    - name: Stop postgresql
      service:
        name: postgresql
        state: stopped

    - name: Run pg_basebackup in replication mode
      ansible.builtin.shell: "mv /var/lib/postgresql/13/main /var/lib/postgresql/13/main_old_remove"
      vars:
        target_group: postgresql-main-private

    - name: Run pg_basebackup in replication mode
      ansible.builtin.shell: "pg_basebackup -h {{ groups[target_group][0] }} -U repuser --checkpoint=fast -D /var/lib/postgresql/13/main -R --slot=repslot01 -C"
      vars:
        target_group: postgresql-main-private

    - name: Start postgresql
      service:
        name: postgresql
        state: started

  vars:
    target_group: postgresql-main

  become: yes
