- block:
    - name: Stop PostgreSQL service on replica node
      ansible.builtin.systemd:
        name: postgresql.service
        state: stopped
  become: yes

- block:
    - name: Backing up original main
      ansible.builtin.shell: "mv /var/lib/postgresql/13/main /var/lib/postgresql/13/main_old_remove"

    - name: Prepare target directory w/ permission 0700
      ansible.builtin.file:
        path: /var/lib/postgresql/13/main
        state: directory
        mode: "0700"

    - name: Run pg_basebackup in replication mode
      ansible.builtin.shell: "pg_basebackup -h {{ main_db_private_ip }} -U repuser --checkpoint=fast -D /var/lib/postgresql/13/main -P -R --slot=repslot01 -C"

    - name: Make sure standby.signal file exists
      ansible.builtin.shell: "touch /var/lib/postgresql/13/main/standby.signal"

  become: yes
  become_user: postgres

- block:
    - name: Start PostgreSQL service on replica node
      ansible.builtin.systemd:
        name: postgresql.service
        state: started
  become: yes
