---
- name: Install service packages
  become: yes
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    state: latest
    update_cache: yes
  loop:
    - gnupg2
    - git
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - curl
  tags:
    - dependencies

- include_tasks: install.yml
