---
- hosts: database-main
  remote_user: admin
  become: yes
  roles:
    - database-create
    - dbserver-reset-replication # just in case

- hosts: database-replica
  remote_user: admin
  become: yes
  roles:
    - dbserver-run-replication
