output "vpc_id" {
  value = module.net.vpc_id
}

output "vm_database_id" {
  value = module.vm_database.vm_id
}

output "vm_database_public_ip" {
  value = module.vm_database.*.public_ip
}

output "vm_database_public_dns" {
  value = module.vm_database.*.public_dns
}

output "vm_database_private_ip" {
  value = module.vm_database.*.private_ip
}

output "vm_database_private_dns" {
  value = module.vm_database.*.private_dns
}

# Export Terraform variable values to an Ansible var_file
resource "local_file" "tf_ansible_vars" {
  content  = <<-DOC
# Ansible vars_file containing variable values from Terraform.
# Generated by Terraform mgmt configuration.

tf_region: ${data.aws_region.current.name}
tf_vm_database_vm_id: ${module.vm_database.vm_id}
%{for s in module.vm_database.*.public_ip~}
tf_vm_database_public_ip: ${s}
%{endfor~}
%{for s in module.vm_database.*.public_dns~}
tf_vm_database_public_dns: ${s}
%{endfor~}
%{for s in module.vm_database.*.private_ip~}
tf_vm_database_private_ip: ${s}
%{endfor~}
%{for s in module.vm_database.*.private_dns~}
tf_vm_database_private_dns: ${s}
%{endfor~}

DOC
  filename = format("%s/%s_%s.yml", var.ansible_directory, "tf_aws", data.aws_region.current.name)
}
